name: Workflow - example

on:
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/example_workflow.yml'
  push:
    paths:
      - 'src/**'
      - '.github/workflows/example_workflow.yml'
    branches:
      - main


jobs:
  job_1:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: print job run
      run: echo "Job 1 run"


  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: print job run
        run: echo "job 2 run."
